### ISSUE TITLE
atm 虛擬帳戶的訂單狀態多了好幾筆

### ISSUE THREAD

**Issue by threeus** [ECPay/OpenCart3.X#2]
atm 的號碼沒變
但是訂單狀態多了好幾筆
![2020-07-17-07_19_48](https://user-images.githubusercontent.com/1575810/87731855-07850480-c7fe-11ea-8bf0-beeaea6686df.jpg)

**Comment by adelachang0418** [comment]
您好,再麻煩協助提供以下資料,以釐清問題
*購物車版本：
*模組版本：
*PHP 版本：
*重現方式：
*是否客製化模組：
若有使用 Plugin 請提供名稱與版本:

非常感謝您

**Comment by AllennChang** [comment]
感謝您的提問, 因一直未收到回覆,固先close 這個問題, 若有任何問題 歡迎再跟我們反應,
