### ISSUE TITLE
$this->url->link 引數

### ISSUE THREAD

**Issue by CharlesCSChang** [ECPay/OpenCart3.X#5]
OpenCart3.X/Source/upload/catalog/controller/extension/shipping/ecpaylogistic.php
Line #159 是否少一個 引數 ?
$this->response->redirect($this->url->link($this->ecpay_payment_module_path . '/redirect','',$this->url_secure));

**Comment by lin1987www** [comment]
我也正想回報這問題，我想應該是的

**Comment by AllennChang** [comment]
您好, 已收到你們回報的問題, 已請開發團隊進行研究, 感謝您們的回報

**Comment by AllennChang** [comment]
您們好, 已經確認有問題並已更新 ,感謝您們的回報
