### ISSUE TITLE
物流沒有回傳即時貨態

### ISSUE THREAD

**Issue by h266579110** [ECPay/OpenCart3.X#6]
![image](https://user-images.githubusercontent.com/14806222/147337615-e64191f3-904d-461f-8003-a17768395fed.png)

環境：
PHP 7.4.26
Opencart 3.0.3.8

**Comment by AllennChang** [comment]
您好, 感謝您的詢問,  回覆如下, 

貨態更新是以批次交換檔案方式進行
是由超商端提供貨態給予綠界科技後，
依排程回傳更新綠界廠商管理後台貨態，
若您ServerReplyURL持續未收到貨態更新，亦可使用物流訂單查詢API進行反查
https://logistics.ecpay.com.tw/Helper/QueryLogisticsTradeInfo/V2 
另外，貨態也會因物流配送過程異常而導致貨態停滯
超商端亦有提供即時貨態追蹤，如有需要可至超商端直接查詢。

若有不清楚的地方,歡迎再跟我們反應, 感謝您
