### ISSUE TITLE
Ecpaylogistic 中有無效的程式碼

### ISSUE THREAD

**Issue by lin1987www** [ECPay/OpenCart3.X#8]
https://github.com/ECPay/OpenCart3.X/blob/ed139d934d3d468346b8f8457945170b4ca0ef18/Source/upload/catalog/controller/extension/payment/ecpaylogistic.php#L146

&$data 指的是 呼叫 method 所帶入的 arguments 但我目前觀察呼叫 catalog/model/setting/extension/getExtensions
修改其 arguments 並不會對程式造成任何影響

因此建議刪除146~148行

**Comment by AllennChang** [comment]
您好, 已收到您反應的問題, 會請開發團隊進行評估, 感謝您的回饋

**Comment by AllennChang** [comment]
您好, 您反應的問題經開發團隊評估後是可以刪除的, 已經完成調整也上架的GITHUB, 再次感謝您的回饋, 感謝
